name = "workers-ai-to-openai"
main = "index.js"
compatibility_date = "2024-07-29"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "openai-cf-images"

[vars]
CLOUDFLARE_ACCOUNT_ID = "b0dda00db555f237f277259bed93134b"
# MODEL_MAPPER = { "gpt-3.5-turbo" = "@cf/meta/llama-2-7b-chat-int8" } # Optional
