name = "ai-to-openai"                # todo
main = "index.js"
compatibility_date = "2024-05-06"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "ai-to-openai-images"

[vars]
CLOUDFLARE_ACCOUNT_ID = "b0dda00db555f237f277259bed93134b"
# MODEL_MAPPER = { "gpt-3.5-turbo" = "@cf/meta/llama-2-7b-chat-int8" } # Optional
